//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dz1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyId { get; set; }
        public int GoodId { get; set; }
        public Nullable<int> GoodCount { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Summa { get; set; }
        public int DistiId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Disti Disti { get; set; }
        public virtual Good Good { get; set; }
    }
}
